# Generated by Django 2.0.8 on 2018-11-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentedproperties', '0002_auto_20181126_1636'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='the_property',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rentedproperties.Property'),
        ),
    ]
