# Generated by Django 2.0.8 on 2018-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentedproperties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
    ]
