# Generated by Django 2.0.8 on 2018-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentedproperties', '0003_auto_20181129_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='landlord',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
    ]
