# Generated by Django 2.0.8 on 2018-11-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentedproperties', '0005_auto_20181129_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilew', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
